// Deterministic build for com.ikenga.finance — WP-20b (8-step recipe, step 2).
//
// 1. Vendor tokens-css.js + app-kit-css.js from @ikenga/tokens (single source of truth).
// 2. Codegen finance-css.js from dist/finance.css via JSON.stringify (no drift).
//
// CSS rides the script path because WebKitGTK cannot load subresources from the
// about:srcdoc the shell mounts; app.js injects each as an inline <style>.
// Guard drift in CI: `pnpm -r build && git diff --exit-code`.
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { vendorRuntime } from '../../../lib/pkg-runtime/vendor.mjs';

const require = createRequire(import.meta.url);
mkdirSync('dist/lib', { recursive: true });

// 1. Vendor reconciled token JS-strings from installed @ikenga/tokens.
copyFileSync(require.resolve('@ikenga/tokens/tokens-css'), 'dist/lib/tokens-css.js');
copyFileSync(require.resolve('@ikenga/tokens/app-kit-css'), 'dist/lib/app-kit-css.js');

// 2. Codegen domain CSS string from dist/finance.css.
const css = readFileSync('dist/finance.css', 'utf8');
const header =
  '// GENERATED by scripts/build.mjs from dist/finance.css — do not edit.\n' +
  '// CSS-as-string: WebKitGTK cannot load link/fetch subresources from the\n' +
  '// about:srcdoc the shell mounts, so app.js injects this as an inline <style>.\n';
writeFileSync('dist/lib/finance-css.js', header + 'export default ' + JSON.stringify(css) + '\n');

// 3. Vendor the shared no-build runtime (bridge + ui) from @ikenga/pkg-runtime —
//    single source of truth (WP-19). pkg-id.js carries this pkg's source-id +
//    log tag, keeping bridge.js byte-identical across pkgs.
const runtime = vendorRuntime({
  destLibDir: fileURLToPath(new URL('../dist/lib', import.meta.url)),
  pkgId: 'com.ikenga.finance',
  logTag: 'finance',
  files: ['bridge', 'ui'],
});

console.log(
  '[finance build] vendored tokens-css.js + app-kit-css.js + regenerated finance-css.js from dist/finance.css; runtime: ' +
    runtime.join(', '),
);
