// Deterministic build for com.ikenga.content — WP-21b (wave-3 domain pkg).
//
// Follows the WP-16..23 recipe exactly (the 8-step spine):
//   1. tokens-css.js is COPIED from @ikenga/tokens (single source of truth).
//   2. app-kit-css.js is COPIED from @ikenga/tokens (kit primitives content consumes).
//   3. content-css.js is CODEGEN'd from dist/content.css via JSON.stringify.
//
// CSS files ride the script path (not <link>/@import) because WebKitGTK cannot
// load subresources from the about:srcdoc the shell mounts; app.js injects each
// as an inline <style>. Guard against drift in CI with:
//   pnpm -r build && git diff --exit-code
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
mkdirSync('dist/lib', { recursive: true });

// 1. Vendor the reconciled tokens JS-string from the installed @ikenga/tokens.
copyFileSync(require.resolve('@ikenga/tokens/tokens-css'), 'dist/lib/tokens-css.js');

// 2. Vendor the app-kit component layer — the kit primitives content consumes
//    (.frame*, .ip-*, .dense-row*, .badge, .chip, .tag, .btn*, .atelier-state.*,
//    .nav-group*, .nav-item*, .kb-*, .seg*, .split-*, etc.). Copied from the same
//    installed @ikenga/tokens so it can never drift; app.js injects it between
//    tokens-css and content-css (tokens → app-kit → domain residue).
copyFileSync(require.resolve('@ikenga/tokens/app-kit-css'), 'dist/lib/app-kit-css.js');

// 3. Regenerate the domain CSS string from dist/content.css (the source of truth).
const css = readFileSync('dist/content.css', 'utf8');
const header =
  '// GENERATED by scripts/build.mjs from dist/content.css — do not edit.\n' +
  '// CSS-as-string: WebKitGTK cannot load link/fetch subresources from the\n' +
  '// about:srcdoc the shell mounts, so app.js injects this as an inline <style>.\n';
writeFileSync('dist/lib/content-css.js', header + 'export default ' + JSON.stringify(css) + '\n');

console.log('[content build] vendored tokens-css.js + app-kit-css.js + regenerated content-css.js from dist/content.css');
