// Deterministic build for com.ikenga.outbound — WP-16..23 recipe, step 2.
//
// Mirrors the tasks + mail pkg builds exactly (same three-step pattern):
//   1. tokens-css.js is COPIED from @ikenga/tokens (single source of truth).
//   2. app-kit-css.js is COPIED from @ikenga/tokens (kit primitives outbound consumes).
//   3. outbound-css.js is CODEGEN'd from dist/outbound.css via JSON.stringify.
//
// Both token files ride the script path (not <link>/@import) because WebKitGTK
// cannot load subresources from the about:srcdoc the shell mounts; app.js injects
// each as an inline <style>. Guard against drift in CI with:
//   pnpm -r build && git diff --exit-code
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { vendorRuntime } from '../../../lib/pkg-runtime/vendor.mjs';

const require = createRequire(import.meta.url);
mkdirSync('dist/lib', { recursive: true });

// 1. Vendor the reconciled tokens JS-string from the installed @ikenga/tokens.
copyFileSync(require.resolve('@ikenga/tokens/tokens-css'), 'dist/lib/tokens-css.js');

// 2. Vendor the app-kit component layer — the kit primitives outbound consumes
//    (.frame*, .ip-*, .dense-row*, .badge, .chip, .tag, .btn*, .nav-group*,
//    .nav-item*, .atelier-state.*, .ob-actions*, .cmdk, etc.). Copied from the
//    same installed @ikenga/tokens so it can never drift; app.js injects it
//    between tokens-css and outbound-css (tokens → app-kit → domain residue).
copyFileSync(require.resolve('@ikenga/tokens/app-kit-css'), 'dist/lib/app-kit-css.js');

// 3. Regenerate the domain CSS string from dist/outbound.css (the source of truth).
const css = readFileSync('dist/outbound.css', 'utf8');
const header =
  '// GENERATED by scripts/build.mjs from dist/outbound.css — do not edit.\n' +
  '// CSS-as-string: WebKitGTK cannot load link/fetch subresources from the\n' +
  '// about:srcdoc the shell mounts, so app.js injects this as an inline <style>.\n';
writeFileSync('dist/lib/outbound-css.js', header + 'export default ' + JSON.stringify(css) + '\n');

// 4. Vendor the shared no-build runtime (bridge + ui) from @ikenga/pkg-runtime —
//    single source of truth (WP-19). outbound's host.fetch + approve-gate verbs
//    ride the 'outbound' bridge fragment appended onto the core. pkg-id.js carries
//    this pkg's source-id + log tag.
const runtime = vendorRuntime({
  destLibDir: fileURLToPath(new URL('../dist/lib', import.meta.url)),
  pkgId: 'com.ikenga.outbound',
  logTag: 'outbound',
  files: ['bridge', 'ui'],
  bridgeExt: 'outbound',
});

console.log(
  '[outbound build] vendored tokens-css.js + app-kit-css.js + regenerated outbound-css.js from dist/outbound.css; runtime: ' +
    runtime.join(', '),
);
