// Deterministic build for com.ikenga.sales — WP-18b (wave-2 domain pkg).
//
// Follows the WP-16..23 recipe exactly (the 8-step spine):
//   1. tokens-css.js is COPIED from @ikenga/tokens (single source of truth).
//   2. app-kit-css.js is COPIED from @ikenga/tokens (kit primitives sales consumes).
//   3. sales-css.js is CODEGEN'd from dist/sales.css via JSON.stringify.
//
// CSS files ride the script path (not <link>/@import) because WebKitGTK cannot
// load subresources from the about:srcdoc the shell mounts; app.js injects each
// as an inline <style>. Guard against drift in CI with:
//   pnpm -r build && git diff --exit-code
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { vendorRuntime } from '../../../lib/pkg-runtime/vendor.mjs';

const require = createRequire(import.meta.url);
mkdirSync('dist/lib', { recursive: true });

// 1. Vendor the reconciled tokens JS-string from the installed @ikenga/tokens.
copyFileSync(require.resolve('@ikenga/tokens/tokens-css'), 'dist/lib/tokens-css.js');

// 2. Vendor the app-kit component layer — the kit primitives sales consumes
//    (.frame*, .ip-*, .dense-row*, .badge, .chip, .tag, .btn*, .atelier-state.*,
//    .nav-group*, .nav-item*, .kb-*, .seg*, .split-*, etc.). Copied from the same
//    installed @ikenga/tokens so it can never drift; app.js injects it between
//    tokens-css and sales-css (tokens → app-kit → domain residue).
copyFileSync(require.resolve('@ikenga/tokens/app-kit-css'), 'dist/lib/app-kit-css.js');

// 3. Regenerate the domain CSS string from dist/sales.css (the source of truth).
const css = readFileSync('dist/sales.css', 'utf8');
const header =
  '// GENERATED by scripts/build.mjs from dist/sales.css — do not edit.\n' +
  '// CSS-as-string: WebKitGTK cannot load link/fetch subresources from the\n' +
  '// about:srcdoc the shell mounts, so app.js injects this as an inline <style>.\n';
writeFileSync('dist/lib/sales-css.js', header + 'export default ' + JSON.stringify(css) + '\n');

// 4. Vendor the shared no-build runtime (bridge + ui + recipe helpers) from
//    @ikenga/pkg-runtime — single source of truth (WP-19). pkg-id.js carries
//    this pkg's source-id + log tag, keeping bridge.js byte-identical across pkgs.
const runtime = vendorRuntime({
  destLibDir: fileURLToPath(new URL('../dist/lib', import.meta.url)),
  pkgId: 'com.ikenga.sales',
  logTag: 'sales',
  files: ['bridge', 'ui', 'dispatch', 'create-dispatch', 'facet-filter'],
});

console.log(
  '[sales build] vendored tokens-css.js + app-kit-css.js + regenerated sales-css.js from dist/sales.css; runtime: ' +
    runtime.join(', '),
);
