// Deterministic build for com.ikenga.agent-ops — WP-19 (runtime extraction) +
// WP-20 (CSS codegen + design conformance).
//
// This pkg previously had `build: echo 'no build'`, then WP-19 vendored the
// shared no-build runtime (bridge + ui) from @ikenga/pkg-runtime — killing its
// copy-pasted bridge.js/ui.js. agent-ops carries the extra `host.agentOps.*`
// cron verbs, so the 'agentops' bridge fragment is appended onto the shared
// core; pkg-id.js injects this pkg's source-id + log tag.
//
// WP-20 closes the CSS gap WP-19 deliberately left open: agent-ops previously
// had NO source `.css` file — its four domain CSS-as-JS artifacts
// (agent-ops-css.js / -runs-css.js / -form-css.js / -live-css.js) were
// hand-escaped template literals, and tokens-css.js was a hand-copied (stale)
// vendor rather than a copy of the published @ikenga/tokens. This script now
// follows the WP-16..23 recipe (see tasks'/sales' build.mjs):
//   1. tokens-css.js is COPIED from the installed @ikenga/tokens (single
//      source of truth — refreshes the stale hand-copied vendor).
//   2. agent-ops-css.js is CODEGEN'd from dist/agent-ops.css (the new real CSS
//      source, extracted verbatim from the four former hand-escaped files;
//      see dist/agent-ops.css's header for provenance) via JSON.stringify.
//
// (agent-ops's CSS is fully self-contained under its own .ao-*/.b-*/.rr-*/
// .rd-* vocabulary — unlike tasks/sales it does not consume @ikenga/tokens'
// app-kit component layer, so app-kit-css.js is not vendored here.)
//
// CSS rides the script path (not <link>/@import) because WebKitGTK cannot
// load subresources from the about:srcdoc the shell mounts; app.js injects it
// as an inline <style>. Guard against drift in CI with:
//   pnpm -r build && git diff --exit-code
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { vendorRuntime } from '../../../lib/pkg-runtime/vendor.mjs';

const require = createRequire(import.meta.url);
mkdirSync('dist/lib', { recursive: true });

// 1. Vendor the reconciled tokens JS-string from the installed @ikenga/tokens.
copyFileSync(require.resolve('@ikenga/tokens/tokens-css'), 'dist/lib/tokens-css.js');

// 2. Regenerate the domain CSS string from dist/agent-ops.css (the source of truth).
const css = readFileSync('dist/agent-ops.css', 'utf8');
const header =
  '// GENERATED by scripts/build.mjs from dist/agent-ops.css — do not edit.\n' +
  '// CSS-as-string: WebKitGTK cannot load link/fetch subresources from the\n' +
  '// about:srcdoc the shell mounts, so app.js injects this as an inline <style>.\n';
writeFileSync('dist/lib/agent-ops-css.js', header + 'export default ' + JSON.stringify(css) + '\n');

// 3. Vendor the shared no-build runtime (bridge + ui) from @ikenga/pkg-runtime —
//    single source of truth (WP-19). pkg-id.js carries this pkg's source-id +
//    log tag, keeping bridge.js byte-identical across pkgs. agent-ops carries
//    the extra `host.agentOps.*` cron verbs via the 'agentops' bridge fragment.
const runtime = vendorRuntime({
  destLibDir: fileURLToPath(new URL('../dist/lib', import.meta.url)),
  pkgId: 'com.ikenga.agent-ops',
  logTag: 'agent-ops',
  files: ['bridge', 'ui'],
  bridgeExt: 'agentops',
});

console.log(
  '[agent-ops build] vendored tokens-css.js + regenerated agent-ops-css.js from dist/agent-ops.css; runtime: ' +
    runtime.join(', '),
);
