// @ikenga/pkg-runtime — vendor step (WP-19).
//
// The no-build app pkgs (tasks/mail/sales/outbound/content/research/strategy/
// finance/agent-ops) serve their dist/ directly as about:srcdoc iframes, so
// they cannot import across packages at runtime. Instead each pkg's
// scripts/build.mjs calls `vendorRuntime(...)` to COPY this shared runtime into
// its own dist/lib — making dist self-contained while keeping ONE source of
// truth here. This is a build-time (Node) import only; nothing here ships.
//
// The per-pkg identity (source-id + short log tag) is injected as a generated
// sibling `pkg-id.js` that bridge.js imports, so the vendored bridge.js is
// BYTE-IDENTICAL across every pkg — killing the copy-paste-id bug class. Pkgs
// with extra host surface (outbound's host.fetch + approve-gate, agent-ops'
// host.agentOps.*) append a fragment onto the core via `bridgeExt`.
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const RUNTIME_DIR = dirname(fileURLToPath(import.meta.url));

// bridgeExt key → concatenation fragment appended after the bridge core.
const EXT_FILE = {
  outbound: 'bridge.ext.outbound.js',
  agentops: 'bridge.ext.agentops.js',
};

function renderPkgId(pkgId, logTag) {
  return (
    '// GENERATED by @ikenga/pkg-runtime vendor step — do not edit.\n' +
    '// Per-pkg identity injected into the shared bridge.js core so the runtime\n' +
    '// stays byte-identical across pkgs (WP-19). Overwritten on next build.\n' +
    `export const PKG_ID = ${JSON.stringify(pkgId)};\n` +
    `export const LOG_TAG = ${JSON.stringify(logTag)};\n`
  );
}

/**
 * Vendor the shared no-build runtime into a pkg's dist/lib.
 *
 * @param {object}   opts
 * @param {string}   opts.destLibDir  absolute path to the pkg's dist/lib
 * @param {string}   opts.pkgId       manifest id, e.g. 'com.ikenga.sales'
 * @param {string}   opts.logTag      short console/error tag, e.g. 'sales'
 * @param {string[]} opts.files       runtime module basenames to vendor. 'bridge'
 *                                     also emits the generated pkg-id.js. Others:
 *                                     'ui' | 'dispatch' | 'facet-filter' | 'create-dispatch'.
 * @param {'outbound'|'agentops'} [opts.bridgeExt]  append a pkg-specific bridge fragment.
 * @returns {string[]} the basenames written into dist/lib (for logging).
 */
export function vendorRuntime({ destLibDir, pkgId, logTag, files, bridgeExt }) {
  mkdirSync(destLibDir, { recursive: true });
  const written = [];
  for (const name of files) {
    if (name === 'bridge') {
      writeFileSync(join(destLibDir, 'pkg-id.js'), renderPkgId(pkgId, logTag));
      let out = readFileSync(join(RUNTIME_DIR, 'bridge.js'), 'utf8');
      if (bridgeExt) {
        const frag = EXT_FILE[bridgeExt];
        if (!frag) throw new Error(`[pkg-runtime] unknown bridgeExt: ${bridgeExt}`);
        const ext = readFileSync(join(RUNTIME_DIR, frag), 'utf8');
        out = out.replace(/\n$/, '') + '\n' + ext;
      }
      writeFileSync(join(destLibDir, 'bridge.js'), out);
      written.push('pkg-id.js', 'bridge.js');
    } else {
      copyFileSync(join(RUNTIME_DIR, `${name}.js`), join(destLibDir, `${name}.js`));
      written.push(`${name}.js`);
    }
  }
  return written;
}
